### ISSUE TITLE
Handle Memory size

### ISSUE THREAD

**Issue by StevenMHernandez** [StevenmHernandez/cmsc312-operating-system-simulator#11]
We can only add a process if there is enough memory to do so.
We need to set that memory size limit someplace.

**Comment by lobbypolice** [comment]
added memory class, do we need to add anything else to it? should we add methods for checking if a process can be added or should we do that somewhere else

**Comment by StevenMHernandez** [comment]
I guess I didn't see this comment. I think we are good, closing the issue.
